version: '3.7'
services:
  mysql_db_container:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # root账号密码
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080
  nuxt_app_container:
    container_name: nuxt_app
    restart: always
    #构建容器
    build: .
    #直接从git拉去
    # build: git@github.com:su37josephxia/docker_ci.git#:backend
    # 需要链接本地代码时
    # volumes:
    #   - ./backend:/usr/src/app
    ports:
      - "3004:3000"
    environment:
      DATABASE_URL: mysql://root:rootpassword@mysql_db_container:3306/ycxt
      NUXT_BASE_URL: https://jsonplaceholder.typicode.com
      JSON_SECRET: thisisjsonsecret
    command: >
      /bin/sh -c 'npm run migrate && npm run build && npm start'
    depends_on:
      mysql_db_container:
        condition: service_healthy
volumes:
  mysql_db_data_container:
